### PR TITLE
Add extension method to retrieve the collection of rules from a struc…

### PR DESCRIPTION
**Pull request by merijndejonge**
This pull requests adds an extension method and corresponding unit tests for retrieving the collection of TldRules from a structure. This is needed for more advanced rule providers, such as rule combinators that combine the rules from multiple rule providers. Since the parsed rules are pretty-much hidden in the structure, this extension method is needed to provide access to the rules.

### CODE REVIEW

**Comment by tinohager** [comment]
somehow I think there are too many changes in the pull request

**Comment by merijndejonge** [comment]
This pull requests only adds a single extension method and corresponding unit tests. Please reconsider

**Comment by merijndejonge** [comment]
@tinohager any problems with this pull request that adds an extension method for retrieving the collection of TldRules from a structure?

**Comment by tinohager** [comment]
I would like to know the reason for the extension. Why are the domains that you still need not listed in the official list?

Why should it be integrated into the main library and not be an add-on package?

**Comment by merijndejonge** [comment]
- Implement the extension method in an add-on package is no big deal. Actually, that is how I'm currently using it. But I propose to donate it so that more people can use it and such that everything is contained in one code base that needs to be maintained.
- The TldRules in a DomainDataStructure are hidden and cannot be accessed easily.  There are AddTule/AddRules methods but no corresponding GetRule/GetRules methods. I don't see what the reason is for the asymmetric design. This hampers e.g., inspection of the rules once they are consumed by a DomainDataStructure. The proposed extension method makes your design more symmetric (which is another reason to put in your code base :-) )
- I use your library for the implementation of a password manager. The passwords follow public suffix rules. However, for this application, the public suffix list is far from complete. For instance, an organisation like auth0.com uses different identity systems for its subdomains (e.g., customera.auth0.com and customerb.auth0.com). With the information from just the public suffix list, we cannot distinguish between passwords from different customers. Therefore we add auth0.com as an extra entry to solve this. Your library is extremely useful for this, but just a bit too limited. With a few small modifications the design improves making room for use cases like mine.

**Pull request merged**
